/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pgy.ui;
import com.pgy.business.Cliente;
import com.pgy.business.Cuenta;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;

/**
 *
 * @author adsan
 */
public class Ventana_Consultar_Monto_Total_Cancelado extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Consultar_Monto_Total_Cancelado
     */
    public Ventana_Consultar_Monto_Total_Cancelado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRut = new javax.swing.JLabel();
        lblMontoTotalCancelado = new javax.swing.JLabel();
        btnRut = new javax.swing.JButton();
        btnMontoTotalCancelado = new javax.swing.JButton();
        txtRut = new javax.swing.JTextField();
        txtMontoTotalCancelado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblRut.setText("Rut");

        lblMontoTotalCancelado.setText("Monto Total Cancelado");

        btnRut.setText("BUSCAR");
        btnRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRutActionPerformed(evt);
            }
        });

        btnMontoTotalCancelado.setText("CERRAR");
        btnMontoTotalCancelado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMontoTotalCanceladoActionPerformed(evt);
            }
        });

        txtRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRut, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMontoTotalCancelado)
                            .addComponent(lblMontoTotalCancelado, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRut)
                            .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMontoTotalCancelado, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblRut)
                .addGap(25, 25, 25)
                .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRut)
                .addGap(27, 27, 27)
                .addComponent(lblMontoTotalCancelado)
                .addGap(27, 27, 27)
                .addComponent(txtMontoTotalCancelado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnMontoTotalCancelado)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRutActionPerformed

    private void btnRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRutActionPerformed
String rutCliente = txtRut.getText();

// Validar que el RUT no esté vacío
if (rutCliente == null || rutCliente.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Por favor ingresa un RUT válido.", "Error", JOptionPane.ERROR_MESSAGE);
    return; // Salir si el RUT no es válido
}

try {
    Cuenta cuenta = new Cuenta().obtenerCuenta(rutCliente);

    // Verificar si la cuenta existe y tiene datos
    if (cuenta != null) {
        lblMontoTotalCancelado.setText(String.format("%.2f", cuenta.getValorCuota())); // Formato para monto
        //lblRut.setText(cuenta.getRut());
    } else {
        JOptionPane.showMessageDialog(this, "No se encontró cuenta para el RUT ingresado.", "Error", JOptionPane.ERROR_MESSAGE);
    }
} catch (Exception ex) {
    // Manejo general de otras excepciones
    Logger.getLogger(Ventana_Consultar_Monto_Total_Cancelado.class.getName()).log(Level.SEVERE, null, ex);
    JOptionPane.showMessageDialog(this, "Hubo un problema al obtener la cuenta. Intenta nuevamente.", "Error", JOptionPane.ERROR_MESSAGE);
}

    }//GEN-LAST:event_btnRutActionPerformed

    private void btnMontoTotalCanceladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMontoTotalCanceladoActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Funcionalidades en la proxima version :D");        // TODO add your handling code here:
    }//GEN-LAST:event_btnMontoTotalCanceladoActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMontoTotalCancelado;
    private javax.swing.JButton btnRut;
    private javax.swing.JLabel lblMontoTotalCancelado;
    private javax.swing.JLabel lblRut;
    private javax.swing.JTextField txtMontoTotalCancelado;
    private javax.swing.JTextField txtRut;
    // End of variables declaration//GEN-END:variables
}
