package com.pgy.ui;
import javax.swing.JFrame;
import com.pgy.business.Cliente;
import com.pgy.business.Cuenta;
import java.util.ArrayList;
import javax.accessibility.AccessibleContext;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JRootPane;

public class Ventana1 extends javax.swing.JFrame {
    public static ArrayList<Cuenta> cuentaArray;
    
    public Ventana1() {
        initComponents();
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCuentaSocios = new javax.swing.JButton();
        lblSocios = new javax.swing.JLabel();
        lvlCuentaSocios = new javax.swing.JLabel();
        cbSocios = new javax.swing.JComboBox<>();
        cbCuentaSocios = new javax.swing.JComboBox<>();
        btnSocios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCuentaSocios.setText("BUSCAR");
        btnCuentaSocios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuentaSociosActionPerformed(evt);
            }
        });

        lblSocios.setText("Socios");

        lvlCuentaSocios.setText("Cuenta Socios");

        cbSocios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Registrar Socio", "Ver Datos Socio" }));
        cbSocios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSociosActionPerformed(evt);
            }
        });

        cbCuentaSocios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pagar Cuota Mensual", "Consultar Monto Total Cancelado", "Consultar N° Cuotas por Cancelar" }));

        btnSocios.setText("BUSCAR");
        btnSocios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSociosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSocios)
                    .addComponent(btnSocios)
                    .addComponent(cbSocios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbCuentaSocios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCuentaSocios)
                    .addComponent(lvlCuentaSocios))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSocios)
                    .addComponent(lvlCuentaSocios))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSocios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCuentaSocios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCuentaSocios)
                    .addComponent(btnSocios))
                .addGap(81, 81, 81))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbSociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSociosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSociosActionPerformed

    private void btnCuentaSociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuentaSociosActionPerformed

        int indiceCuentaSocios = cbCuentaSocios.getSelectedIndex();
        String cuentaSocios = cbCuentaSocios.getItemAt(indiceCuentaSocios);
        
        switch (cuentaSocios){
            case "Pagar Cuota Mensual":
                Ventana_Pagar_Cuota_Mensual ventanaPagarCuotaMensual = new Ventana_Pagar_Cuota_Mensual();
                ventanaPagarCuotaMensual.setVisible(true);
                break;
            case "Consultar Monto Total Cancelado":
                Ventana_Consultar_Monto_Total_Cancelado ventanaConsultarMontoTotalCancelado = new Ventana_Consultar_Monto_Total_Cancelado();
                ventanaConsultarMontoTotalCancelado.setVisible(true);
                break;
            case "Consultar N° Cuotas por Cancelar":
                Ventana_Consulta_Numero_Cuotas_Faltantes ventanaConsultaNumeroCuotasFaltantes= new Ventana_Consulta_Numero_Cuotas_Faltantes();
                ventanaConsultaNumeroCuotasFaltantes.setVisible(true);
                break;
        }
    }//GEN-LAST:event_btnCuentaSociosActionPerformed

    private void btnSociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSociosActionPerformed
        
        int indiceSocio = cbSocios.getSelectedIndex();
        String socio = cbSocios.getItemAt(indiceSocio);
        
        switch (socio){
            case "Registrar Socio":
                Ventana_Registrar_Socios ventanaRegistrarSocios = new Ventana_Registrar_Socios();
                ventanaRegistrarSocios.setVisible(true);
                break;
            case "Ver Datos Socio":
                Ventana_Ver_Datos_Socios ventanaVerDatosSocios = new Ventana_Ver_Datos_Socios();
                ventanaVerDatosSocios.setVisible(true);
                break;
        }
    }//GEN-LAST:event_btnSociosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCuentaSocios;
    private javax.swing.JButton btnSocios;
    private javax.swing.JComboBox<String> cbCuentaSocios;
    private javax.swing.JComboBox<String> cbSocios;
    private javax.swing.JLabel lblSocios;
    private javax.swing.JLabel lvlCuentaSocios;
    // End of variables declaration//GEN-END:variables


    
}
